version: 2.1

scala_211: &scala_211
  SCALA_VERSION: 2.11.12

scala_212: &scala_212
  SCALA_VERSION: 2.12.8

scala_dotty: &scala_dotty
  SCALA_VERSION: 0.16.0-RC3

jdk_8: &jdk_8
  JDK_VERSION: 8

jdk_11: &jdk_11
  JDK_VERSION: 11

machine_ubuntu: &machine_ubuntu
  machine:
    image: ubuntu-1604:201903-01

install_jdk: &install_jdk
  - run:
      name: Install JDK
      command: |
        while $(ps aux | grep -i ' apt ' | grep -v grep > /dev/null); do sleep 1; done # Wait for apt to be ready
        sudo add-apt-repository ppa:openjdk-r/ppa -y
        sudo apt update
        sudo apt install openjdk-${JDK_VERSION}-jdk -y

load_cache: &load_cache
  - restore_cache:
      key: sbt-metrics-cache

save_cache: &save_cache
  - save_cache:
      key: sbt-metrics-cache
      paths:
          - "~/.ivy2/cache"
          - "~/.sbt"
          - "~/.m2"
          - "~/website/node_modules"

install_yarn: &install_yarn
  - run:
      name: Install Yarn
      command: |
        curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
        sudo bash -c 'echo "deb https://dl.yarnpkg.com/debian/ stable main" > /etc/apt/sources.list.d/yarn.list'
        sudo apt update && sudo apt install yarn -y
        yarn policies set-version
        yarn -v

install_nodejs: &install_nodejs
  - run:
      name: Install node.js
      command: |
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
        export NVM_DIR="/opt/circleci/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        nvm install
        nvm use
        node -v

compile: &compile
  steps:
    - checkout
    - <<: *load_cache
    - run:
        name: Compile code
        command: ./sbt ++${SCALA_VERSION}! test:compile
    - <<: *save_cache

lint: &lint
  steps:
    - checkout
    - <<: *load_cache
    - run:
        name: Lint code
        command: ./sbt ++${SCALA_VERSION}! check
    - <<: *save_cache

mdoc: &mdoc
  steps:
    - checkout
    - <<: *load_cache
    - run:
        name: Generate documentation
        command: ./sbt ++${SCALA_VERSION}! mdoc
    - <<: *save_cache

test: &test
  steps:
    - checkout
    - <<: *load_cache
    - <<: *install_jdk
    - run:
        name: Run tests
        command: ./sbt ++${SCALA_VERSION}! test
    - <<: *save_cache

release: &release
  steps:
      - checkout
      - run:
          name: Fetch git tags
          command: git fetch --tags
      - <<: *load_cache
      - run:
          name: Write PGP public key
          command: echo -n "${PGP_PUBLIC}" | base64 -d > /tmp/public.asc
      - run:
          name: Write PGP secret key
          command: echo -n "${PGP_SECRET}" | base64 -d > /tmp/secret.asc
      - run:
          name: Release artifacts
          command: ./sbt ++${SCALA_VERSION}! releaseEarly

documentation: &documentation
  steps:
      - checkout
      - <<: *load_cache
      - <<: *install_nodejs
      - <<: *install_yarn
      - run:
          name: Generating docs
          command: sbt ++2.12.8! doc
      - <<: *save_cache

microsite: &microsite
  steps:
      - add_ssh_keys:
          fingerprints:
            - "11:2c:fa:98:69:d8:a1:d5:76:2e:38:d0:91:39:85:ce"
      - checkout
      - <<: *load_cache
      - run: sbt ++2.12.8! microsite/makeMicrosite
      - run: sbt ++2.12.8! microsite/publishMicrosite
      - <<: *save_cache

jobs:
  lint:
    <<: *lint
    <<: *machine_ubuntu
    environment:
      - <<: *scala_212
      - <<: *jdk_8

  compile_dotty:
    <<: *compile
    <<: *machine_ubuntu
    environment:
      - <<: *scala_dotty
      - <<: *jdk_8

  mdoc:
    <<: *mdoc
    <<: *machine_ubuntu
    environment:
      - <<: *scala_212
      - <<: *jdk_8

  test_211_jdk8_jvm:
    <<: *test
    <<: *machine_ubuntu
    environment:
      - <<: *scala_211
      - <<: *jdk_8

  test_212_jdk8_jvm:
    <<: *test
    <<: *machine_ubuntu
    environment:
      - <<: *scala_212
      - <<: *jdk_8

  test_dotty_jdk8_jvm:
    <<: *test
    <<: *machine_ubuntu
    environment:
      - <<: *scala_dotty
      - <<: *jdk_8

  test_211_jdk11_jvm:
    <<: *test
    <<: *machine_ubuntu
    environment:
      - <<: *scala_211
      - <<: *jdk_11

  test_212_jdk11_jvm:
    <<: *test
    <<: *machine_ubuntu
    environment:
      - <<: *scala_212
      - <<: *jdk_11

  test_dotty_jdk11_jvm:
    <<: *test
    <<: *machine_ubuntu
    environment:
      - <<: *scala_dotty
      - <<: *jdk_11

  release_211:
    <<: *release
    <<: *machine_ubuntu
    environment:
      - <<: *scala_211
      - <<: *jdk_8

  release_212:
    <<: *release
    <<: *machine_ubuntu
    environment:
      - <<: *scala_212
      - <<: *jdk_8

  documentation:
    <<: *documentation
    <<: *machine_ubuntu
    environment:
      - <<: *jdk_8

  microsite:
    <<: *microsite
    <<: *machine_ubuntu
    environment:
      - <<: *jdk_8

workflows:
  version: 2
  build:
    jobs:
      - lint:
          filters:
            tags:
              only: /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/
      - test_211_jdk8_jvm:
          requires:
            - lint
          filters:
            tags:
              only: /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/
      - test_212_jdk8_jvm:
          requires:
            - lint
          filters:
            tags:
              only: /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/
      - test_211_jdk11_jvm:
          requires:
            - lint
          filters:
            tags:
              only: /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/
      - test_212_jdk11_jvm:
          requires:
            - lint
          filters:
            tags:
              only: /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/
      - release_211:
          context: Sonatype
          requires:
            - test_211_jdk8_jvm
            - test_211_jdk11_jvm
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/
      - release_212:
          context: Sonatype
          requires:
            - test_212_jdk8_jvm
            - test_212_jdk11_jvm
            - release_211
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/
